---
title: "Simulation_Study"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We need all necessary functions:

```{r functions, echo = FALSE}
nmblk <- function(n, l) {
  b <- n / l # assuming that is an integer
  idx <- sample(seq(1, n - l + 1, by = l), b, replace = TRUE) # Sample between 1 and n - l + 1, 
  # separating by l, b times
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points 
  # decided by idx
}

mvblk <- function(n, l) {
  b <- n / l
  idx <- sample(1:(n - l + 1), b, replace = TRUE) # Sample any starting point between 1 and n - 1 + 1
  # they can overlap
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points
  # decided by idx
}

blkboot <- function(tseries, statistic, R, l) {
  n <- length(tseries) 
  ## observed statistic
  stat <- statistic(tseries) #stat stores a certain statistic of tseries using a function
  ## nonmoving block bootstrap
  nm.stat <- replicate(R, statistic(tseries[nmblk(n, l)])) # finds the statistic of nm bootstrap and repeats R times
  ## moving block bootstrap
  mv.stat <- replicate(R, statistic(tseries[mvblk(n, l)])) # finds the statistic of mv bootstrap and repeats R times
  list(stat = stat, nm.stat = nm.stat, mv.stat = mv.stat) # returns list of three values
}

do1rep <- function(n, theta, sd, l, statistic) {
  x <- arima.sim(list(ar = theta), n = n, sd = sd) 
  
  # sd is the standard deviation of the noise -> true_variance(X_t) = sd^2/(1 - theta^2)
  
  bt <- blkboot(x, statistic, 1000, l) 

 # nm_lower_bound with quantile function
  
  nm_interval = quantile(bt$nm.stat, probs = c(0.025, 0.975))
  mv_interval = quantile(bt$mv.stat, probs = c(0.025, 0.975))
  
  nm_contains = FALSE
  if (nm_interval[1] < 0 && nm_interval[2] > 0)
  {
    nm_contains = TRUE
  }
  mv_contains = FALSE
  if (mv_interval[1] < 0 && mv_interval[2] > 0)
  {
    mv_contains = TRUE
  }
  
  c(bt$stat, sd(bt$nm.stat), nm_interval, nm_contains, sd(bt$mv.stat), mv_interval, mv_contains) 

    # returns statistics and standard error's for nm and mv respectively, standard error (sd(bt$mv.stat) is estimated as the sqrt(sample_variance(X_t) / n)
  
}
```

Let's conduct a simulation study with n = 100, ar = 0.5, and sd = 0.1 (var = 0.01)

```{r functions, echo = False}
options(max.print = 1000000)
ar1 <- function(x) cor(x[-1], x[-length(x)])
m1 <- function(x) mean(x)

my_summary <- function(x)
{
  rm = rowMeans(x)
  c(rm, sd(x[1,]), rm[2] - sd(x[1,]), rm[6] - sd(x[1,]), (rm[2] - sd(x[1,])) / sd(x[1,]), (rm[6] - sd(x[1,])) / sd(x[1,]))
}



```


```{r functions, echo = False}
test.data <- data.frame(
  
   n = c(),
   ar = c(),
   sigma = c(),
   l = c(),
   mean = c(), 
   nm_se = c(),
   nm_lower = c(), 
   nm_upper = c(),
   nm_success = c(),
   mv_se = c(),
   mv_lower = c(), 
   mv_upper = c(),
   mv_success = c(),
   true_se = c(),
   nm_diff = c(),
   mv_diff = c(),
   nm_percent_change = c(),
   mv_percent_change = c()
)

for(n in c(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000))
{
  for(i in 1:3)
  {
    sim <- replicate(100, do1rep(n, 0.1, 0.1, 10, m1))
    m <- my_summary(sim)
    tobind.data <- data.frame(
     n = c(n),
     ar = c(0.1),
     sigma = c(0.1),
     l = c(10),
     mean = c(m[1]), 
     nm_se = c(m[2]),
     nm_lower = c(m[3]), 
     nm_upper = c(m[4]),
     nm_success = c(m[5]),
     mv_se = c(m[6]),
     mv_lower = c(m[7]), 
     mv_upper = c(m[8]),
     mv_success = c(m[9]),
     true_se = c(m[10]),
     nm_diff = c(m[11]),
     mv_diff = c(m[12]),
     nm_percent_diff = c(m[13]),
     mv_percent_diff = c(m[14])
    )
    test.data = rbind(test.data, tobind.data)
  }
}

print(test.data)
```

```{r functions, echo = False}
install.packages("ggplot2")
library(ggplot2)

test_reshaped <- data.frame(x = test.data$n,                           
                       y = c(test.data$nm_percent_diff, test.data$mv_percent_diff),
                       group = c(rep("Non-moving Percent Difference", nrow(test.data)),
                                 rep("Moving Percent Difference", nrow(test.data))))

ggplot(test_reshaped, aes(x, y, col = group)) +  geom_point()

```
```{r functions, echo = False}
test.data <- data.frame(
  
   n = c(),
   ar = c(),
   sigma = c(),
   l = c(),
   mean = c(), 
   nm_se = c(),
   nm_lower = c(), 
   nm_upper = c(),
   nm_success = c(),
   mv_se = c(),
   mv_lower = c(), 
   mv_upper = c(),
   mv_success = c(),
   true_se = c(),
   nm_diff = c(),
   mv_diff = c(),
   nm_percent_change = c(),
   mv_percent_change = c()
)

for(n in c(50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000))
{
  for(i in 1:3)
  {
    sim <- replicate(100, do1rep(n, 0.1, 0.1, 10, m1))
    m <- my_summary(sim)
    tobind.data <- data.frame(
     n = c(n),
     ar = c(0.1),
     sigma = c(0.1),
     l = c(10),
     mean = c(m[1]), 
     nm_se = c(m[2]),
     nm_lower = c(m[3]), 
     nm_upper = c(m[4]),
     nm_success = c(m[5]),
     mv_se = c(m[6]),
     mv_lower = c(m[7]), 
     mv_upper = c(m[8]),
     mv_success = c(m[9]),
     true_se = c(m[10]),
     nm_diff = c(m[11]),
     mv_diff = c(m[12]),
     nm_percent_diff = c(m[13]),
     mv_percent_diff = c(m[14])
    )
    test.data = rbind(test.data, tobind.data)
  }
}

print(test.data)
```

```{r functions, echo = False}
install.packages("ggplot2")
library(ggplot2)

test_reshaped <- data.frame(x = test.data$n,                           
                       y = c(test.data$nm_percent_diff, test.data$mv_percent_diff),
                       group = c(rep("Non-moving Percent Difference", nrow(test.data)),
                                 rep("Moving Percent Difference", nrow(test.data))))

ggplot(test_reshaped, aes(x, y, col = group)) +  geom_point()

```
```{r functions, echo = False}
test.data <- data.frame(
  
   n = c(),
   ar = c(),
   sigma = c(),
   l = c(),
   mean = c(), 
   nm_se = c(),
   nm_lower = c(), 
   nm_upper = c(),
   nm_success = c(),
   mv_se = c(),
   mv_lower = c(), 
   mv_upper = c(),
   mv_success = c(),
   true_se = c(),
   nm_diff = c(),
   mv_diff = c(),
   nm_percent_change = c(),
   mv_percent_change = c()
)

for(n in c(20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500))
{
  for(i in 1:3)
  {
    sim <- replicate(100, do1rep(n, 0.1, 0.1, 10, m1))
    m <- my_summary(sim)
    tobind.data <- data.frame(
     n = c(n),
     ar = c(0.1),
     sigma = c(0.1),
     l = c(10),
     mean = c(m[1]), 
     nm_se = c(m[2]),
     nm_lower = c(m[3]), 
     nm_upper = c(m[4]),
     nm_success = c(m[5]),
     mv_se = c(m[6]),
     mv_lower = c(m[7]), 
     mv_upper = c(m[8]),
     mv_success = c(m[9]),
     true_se = c(m[10]),
     nm_diff = c(m[11]),
     mv_diff = c(m[12]),
     nm_percent_diff = c(m[13]),
     mv_percent_diff = c(m[14])
    )
    test.data = rbind(test.data, tobind.data)
  }
}

print(test.data)
```

```{r functions, echo = False}
install.packages("ggplot2")
library(ggplot2)

test_reshaped <- data.frame(x = test.data$n,                           
                       y = c(test.data$nm_percent_diff, test.data$mv_percent_diff),
                       group = c(rep("Non-moving Percent Difference", nrow(test.data)),
                                 rep("Moving Percent Difference", nrow(test.data))))

ggplot(test_reshaped, aes(x, y, col = group)) +  geom_point()

```
```{r functions, echo = False}
test.data <- data.frame(
  
   n = c(),
   ar = c(),
   sigma = c(),
   l = c(),
   mean = c(), 
   nm_se = c(),
   nm_lower = c(), 
   nm_upper = c(),
   nm_success = c(),
   mv_se = c(),
   mv_lower = c(), 
   mv_upper = c(),
   mv_success = c(),
   true_se = c(),
   nm_diff = c(),
   mv_diff = c(),
   nm_percent_change = c(),
   mv_percent_change = c()
)

for(n in c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250))
{
  for(i in 1:3)
  {
    sim <- replicate(100, do1rep(n, 0.1, 0.1, 10, m1))
    m <- my_summary(sim)
    tobind.data <- data.frame(
     n = c(n),
     ar = c(0.1),
     sigma = c(0.1),
     l = c(10),
     mean = c(m[1]), 
     nm_se = c(m[2]),
     nm_lower = c(m[3]), 
     nm_upper = c(m[4]),
     nm_success = c(m[5]),
     mv_se = c(m[6]),
     mv_lower = c(m[7]), 
     mv_upper = c(m[8]),
     mv_success = c(m[9]),
     true_se = c(m[10]),
     nm_diff = c(m[11]),
     mv_diff = c(m[12]),
     nm_percent_diff = c(m[13]),
     mv_percent_diff = c(m[14])
    )
    test.data = rbind(test.data, tobind.data)
  }
}

print(test.data)
```

```{r functions, echo = False}
install.packages("ggplot2")
library(ggplot2)

test_reshaped <- data.frame(x = test.data$n,                           
                       y = c(test.data$nm_percent_diff, test.data$mv_percent_diff),
                       group = c(rep("Non-moving Percent Difference", nrow(test.data)),
                                 rep("Moving Percent Difference", nrow(test.data))))

ggplot(test_reshaped, aes(x, y, col = group)) +  geom_point()

```












