```{r functions, echo = FALSE}
nmblk <- function(n, l) {
  b <- n / l # assuming that is an integer
  idx <- sample(seq(1, n - l + 1, by = l), b, replace = TRUE) # Sample between 1 and n - l + 1, 
  # separating by l, b times
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points 
  # decided by idx
}

mvblk <- function(n, l) {
  b <- n / l
  idx <- sample(1:(n - l + 1), b, replace = TRUE) # Sample any starting point between 1 and n - 1 + 1
  # they can overlap
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points
  # decided by idx
}

blkboot <- function(tseries, statistic, R, l) {
  n <- length(tseries) 
  ## observed statistic
  stat <- statistic(tseries) #stat stores a certain statistic of tseries using a function
  ## nonmoving block bootstrap
  nm.stat <- replicate(R, statistic(tseries[nmblk(n, l)])) # finds the statistic of nm bootstrap and repeats R times
  ## moving block bootstrap
  mv.stat <- replicate(R, statistic(tseries[mvblk(n, l)])) # finds the statistic of mv bootstrap and repeats R times
  list(stat = stat, nm.stat = nm.stat, mv.stat = mv.stat) # returns list of three values
}

do1rep <- function(n, theta, sd, l, statistic) {
  x <- arima.sim(list(ar = theta), n = n, sd = sqrt((sd^2)*(1-theta^2))) 
  
  # sd is the standard deviation of the noise -> true_variance(X_t) = sd^2/(1 - theta^2)
  
  bt <- blkboot(x, statistic, 1000, l) 

 # nm_lower_bound with quantile function
  
  nm_interval = quantile(bt$nm.stat, probs = c(0.025, 0.975))
  mv_interval = quantile(bt$mv.stat, probs = c(0.025, 0.975))
  
  nm_contains = FALSE
  value = 0
  if (identical(statistic, ar1))
  {
    value = theta
  }
  if (nm_interval[1] < value && nm_interval[2] > value)
  {
    nm_contains = TRUE
  }
  mv_contains = FALSE
  if (mv_interval[1] < value && mv_interval[2] > value)
  {
    mv_contains = TRUE
  }
  
  c(bt$stat, sd(bt$nm.stat), nm_interval, nm_contains, sd(bt$mv.stat), mv_interval, mv_contains) 

    # returns statistics and standard error's for nm and mv respectively, standard error (sd(bt$mv.stat) is estimated as the sqrt(sample_variance(X_t) / n)
  
}

do1rep2 <- function(n, theta, sd, l, statistic) {
  x <- rnorm(n = n, sd = sd)
  
  # sd is the standard deviation of the noise -> true_variance(X_t) = sd^2/(1 - theta^2)
  
  bt <- blkboot(x, statistic, 1000, l) 

 # nm_lower_bound with quantile function
  
  nm_interval = quantile(bt$nm.stat, probs = c(0.025, 0.975))
  mv_interval = quantile(bt$mv.stat, probs = c(0.025, 0.975))
  
  nm_contains = FALSE
  value = 0
  if (identical(statistic, ar1))
  {
    value = theta
  }
    
  if (nm_interval[1] < value && nm_interval[2] > value)
  {
    nm_contains = TRUE
  }
  mv_contains = FALSE
  if (mv_interval[1] < value && mv_interval[2] > value)
  {
    mv_contains = TRUE
  }
  
  c(bt$stat, sd(bt$nm.stat), nm_interval, nm_contains, sd(bt$mv.stat), mv_interval, mv_contains) 

    # returns statistics and standard error's for nm and mv respectively, standard error (sd(bt$mv.stat) is estimated as the sqrt(sample_variance(X_t) / n)
  
}
```

```{r more_functions, echo = False}
options(max.print = 1000000)
ar1 <- function(x) cor(x[-1], x[-length(x)])
#ar1 <- function(x) acf(x, plot = FALSE, lag.max = 1)$acf[2]
m1 <- function(x) mean(x)

my_summary <- function(x)
{
  rm = rowMeans(x)
  c(rm, sd(x[1,]), rm[2] - sd(x[1,]), rm[6] - sd(x[1,]), (rm[2] - sd(x[1,])) / sd(x[1,]), (rm[6] - sd(x[1,])) / sd(x[1,]), rm[5] + qnorm(.975) * sqrt((rm[5] * (1 - rm[5])) / 4000), rm[5] - qnorm(.975) * sqrt((rm[5] * (1 - rm[5])) / 4000),  rm[9] + qnorm(.975) * sqrt((rm[9] * (1 - rm[9])) / 4000), rm[9] - qnorm(.975) * sqrt((rm[9] * (1 - rm[9])) / 4000))
}

```

```{r Normal Sample n = 32}
set.seed(5)
(m_norm_32 = my_summary(replicate(4000, do1rep2(32, 0, 0.1, ceiling(32**(1/3)), m1))))
set.seed(5)
(ar_norm_32 = my_summary(replicate(4000, do1rep2(32, 0, 0.1, ceiling(32**(1/3)), ar1))))
```

```{r Normal Sample n = 64}
set.seed(5)
(m_norm_64 = my_summary(replicate(4000, do1rep2(64, 0, 0.1, ceiling(64**(1/3)), m1))))
set.seed(5)
(ar_norm_64 = my_summary(replicate(4000, do1rep2(64, 0, 0.1, ceiling(64**(1/3)), ar1))))
```

```{r Normal Sample n = 128}
set.seed(5)
(m_norm_128 = my_summary(replicate(4000, do1rep2(128, 0, 0.1, ceiling(128**(1/3)), m1))))
set.seed(5)
(ar_norm_128 = my_summary(replicate(4000, do1rep2(128, 0, 0.1, ceiling(128**(1/3)), ar1))))
```

```{r Normal Sample n = 256}
set.seed(5)
(m_norm_256 = my_summary(replicate(4000, do1rep2(256, 0, 0.1, ceiling(256**(1/3)), m1))))
set.seed(5)
(ar_norm_256 = my_summary(replicate(4000, do1rep2(256, 0, 0.1, ceiling(256**(1/3)), ar1))))
```

```{r Normal Sample n = 512}
set.seed(5)
(m_norm_512 = my_summary(replicate(4000, do1rep2(512, 0, 0.1, ceiling(512**(1/3)), m1))))
set.seed(5)
(ar_norm_512 = my_summary(replicate(4000, do1rep2(512, 0, 0.1, ceiling(512**(1/3)), ar1))))
```

```{r Normal Sample n = 1024}
set.seed(5)
(m_norm_1024 = my_summary(replicate(4000, do1rep2(1024, 0, 0.1, ceiling(1024**(1/3)), m1))))
```

```{r Normal Sample n = 2048}
set.seed(5)
(m_norm_2048 = my_summary(replicate(4000, do1rep2(2048, 0, 0.1, ceiling(2048**(1/3)), m1))))
```

```{r AR = 0.2 Sample n = 32}
set.seed(5)
(m_0.2_32 = my_summary(replicate(4000, do1rep(32, 0.2, 0.1, ceiling(32**(1/3)), m1))))
set.seed(5)
(ar_0.2_32 = my_summary(replicate(4000, do1rep(32, 0.2, 0.1, ceiling(32**(1/3)), ar1))))
```

```{r AR = 0.2 Sample n = 64}
set.seed(5)
(m_0.2_64 = my_summary(replicate(4000, do1rep(64, 0.2, 0.1, ceiling(64**(1/3)), m1))))
set.seed(5)
(ar_0.2_64 = my_summary(replicate(4000, do1rep(64, 0.2, 0.1, ceiling(64**(1/3)), ar1))))
```

```{r AR = 0.2 Sample n = 128}
set.seed(5)
(m_0.2_128 = my_summary(replicate(4000, do1rep(128, 0.2, 0.1, ceiling(128**(1/3)), m1))))
set.seed(5)
(ar_0.2_128 = my_summary(replicate(4000, do1rep(128, 0.2, 0.1, ceiling(128**(1/3)), ar1))))
```

```{r AR = 0.2 Sample n = 256}
set.seed(5)
(m_0.2_256 = my_summary(replicate(4000, do1rep(256, 0.2, 0.1, ceiling(256**(1/3)), m1))))
set.seed(5)
(ar_0.2_256 = my_summary(replicate(4000, do1rep(256, 0.2, 0.1, ceiling(256**(1/3)), ar1))))
```

```{r AR = 0.2 Sample n = 512}
set.seed(5)
(m_0.2_512 = my_summary(replicate(4000, do1rep(512, 0.2, 0.1, ceiling(512**(1/3)), m1))))
set.seed(5)
(ar_0.2_512 = my_summary(replicate(4000, do1rep(512, 0.2, 0.1, ceiling(512**(1/3)), ar1))))
```

```{r AR = 0.2 Sample n = 1024}
set.seed(5)
(m_0.2_1024 = my_summary(replicate(4000, do1rep(1024, 0.2, 0.1, ceiling(1024**(1/3)), m1))))
set.seed(5)
(ar_0.2_1024 = my_summary(replicate(4000, do1rep(1024, 0.2, 0.1, ceiling(1024**(1/3)), ar1))))
```

```{r AR = 0.2 Sample n = 2048}
set.seed(5)
(m_0.2_2048 = my_summary(replicate(4000, do1rep(2048, 0.2, 0.1, ceiling(2048**(1/3)), m1))))
set.seed(5)
(ar_0.2_2048 = my_summary(replicate(4000, do1rep(2048, 0.2, 0.1, ceiling(2048**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 32}
set.seed(5)
(m_0.4_32 = my_summary(replicate(4000, do1rep(32, 0.4, 0.1, ceiling(32**(1/3)), m1))))
set.seed(5)
(ar_0.4_32 = my_summary(replicate(4000, do1rep(32, 0.4, 0.1, ceiling(32**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 64}
set.seed(5)
(m_0.4_64 = my_summary(replicate(4000, do1rep(64, 0.4, 0.1, ceiling(64**(1/3)), m1))))
set.seed(5)
(ar_0.4_64 = my_summary(replicate(4000, do1rep(64, 0.4, 0.1, ceiling(64**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 128}
set.seed(5)
(m_0.4_128 = my_summary(replicate(4000, do1rep(128, 0.4, 0.1, ceiling(128**(1/3)), m1))))
set.seed(5)
(ar_0.4_128 = my_summary(replicate(4000, do1rep(128, 0.4, 0.1, ceiling(128**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 256}
set.seed(5)
(m_0.4_256 = my_summary(replicate(4000, do1rep(256, 0.4, 0.1, ceiling(256**(1/3)), m1))))
set.seed(5)
(ar_0.4_256 = my_summary(replicate(4000, do1rep(256, 0.4, 0.1, ceiling(256**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 512}
set.seed(5)
(m_0.4_512 = my_summary(replicate(4000, do1rep(512, 0.4, 0.1, ceiling(512**(1/3)), m1))))
set.seed(5)
(ar_0.4_512 = my_summary(replicate(4000, do1rep(512, 0.4, 0.1, ceiling(512**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 1024}
set.seed(5)
(m_0.4_1024 = my_summary(replicate(4000, do1rep(1024, 0.4, 0.1, ceiling(1024**(1/3)), m1))))
set.seed(5)
(ar_0.4_1024 = my_summary(replicate(4000, do1rep(1024, 0.4, 0.1, ceiling(1024**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 2048}
set.seed(5)
(m_0.4_2048 = my_summary(replicate(4000, do1rep(2048, 0.4, 0.1, ceiling(2048**(1/3)), m1))))
set.seed(5)
(ar_0.4_2048 = my_summary(replicate(4000, do1rep(2048, 0.4, 0.1, ceiling(2048**(1/3)), ar1))))
```

```{r AR = 0.4 Sample n = 4096}
set.seed(5)
(m_0.4_4096 = my_summary(replicate(4000, do1rep(4096, 0.4, 0.1, ceiling(4096**(1/3)), m1))))
set.seed(5)
(ar_0.4_4096 = my_summary(replicate(4000, do1rep(4096, 0.4, 0.1, ceiling(4096**(1/3)), ar1))))
```

```{r}
#m_norm_1024 <- c(1024, m_norm_1024)
```


```{r}
m_norm <- data.frame(rbind(t(m_norm_32[c(1, 6, 17, 16)]), t(m_norm_32[c(1, 10, 19, 18)]), t(m_norm_64[c(1, 6, 17, 16)]), t(m_norm_64[c(1, 10, 19, 18)]), t(m_norm_128[c(1, 6, 17, 16)]), t(m_norm_128[c(1, 10, 19, 18)]), t(m_norm_256[c(1, 6, 17, 16)]), t(m_norm_256[c(1, 10, 19, 18)]), t(m_norm_512[c(1, 6, 17, 16)]), t(m_norm_512[c(1, 10, 19, 18)]), t(m_norm_1024[c(1, 6, 17, 16)]), t(m_norm_1024[c(1, 10, 19, 18)])))
rownames(m_norm) <- NULL
colnames(m_norm) <- c("n", 'coverage_rate', 'lb', 'ub')
m_norm['method'] <- c('nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv')
library(dplyr)
m_norm[order(-m_norm$n), ]
```

```{r}
ggplot(m_norm, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=0.1) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(~ method) +
  labs(title = 'AR = 0', x = 'Time Series Length', y = 'Confidence Interval Mean Recovery Rate') +
  scale_x_continuous(trans='log2') +
  theme(legend.position="none")
```


```{r}
ar_norm <- data.frame(rbind(t(ar_norm_32[c(1, 6, 17, 16)]), t(ar_norm_32[c(1, 10, 19, 18)]), t(ar_norm_64[c(1, 6, 17, 16)]), t(ar_norm_64[c(1, 10, 19, 18)]), t(ar_norm_128[c(1, 6, 17, 16)]), t(ar_norm_128[c(1, 10, 19, 18)]), t(ar_norm_256[c(1, 6, 17, 16)]), t(ar_norm_256[c(1, 10, 19, 18)]), t(ar_norm_512[c(1, 6, 17, 16)]), t(ar_norm_512[c(1, 10, 19, 18)])))
rownames(ar_norm) <- NULL
colnames(ar_norm) <- c("n", 'coverage_rate', 'lb', 'ub')
ar_norm['method'] <- c('nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv')
library(dplyr)
ar_norm[order(-ar_norm$n), ]
```

```{r}
ggplot(ar_norm, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=0.1) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(~ method) +
  labs(title = 'AR = 0', x = 'Time Series Length', y = 'Confidence Interval AR(1) Coefficient Recovery Rate') +
  scale_x_continuous(trans='log2') +
  theme(legend.position="none")
```

```{r}
m_0.2 <- data.frame(rbind(t(m_0.2_32[c(1, 6, 17, 16)]), t(m_0.2_32[c(1, 10, 19, 18)]), t(m_0.2_64[c(1, 6, 17, 16)]), t(m_0.2_64[c(1, 10, 19, 18)]), t(m_0.2_128[c(1, 6, 17, 16)]), t(m_0.2_128[c(1, 10, 19, 18)]), t(m_0.2_256[c(1, 6, 17, 16)]), t(m_0.2_256[c(1, 10, 19, 18)]), t(m_0.2_512[c(1, 6, 17, 16)]), t(m_0.2_512[c(1, 10, 19, 18)]), t(m_0.2_1024[c(1, 6, 17, 16)]), t(m_0.2_1024[c(1, 10, 19, 18)])))
rownames(m_0.2) <- NULL
colnames(m_0.2) <- c("n", 'coverage_rate', 'lb', 'ub')
m_0.2['method'] <- c('nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv')
library(dplyr)
m_0.2[order(-m_0.2$n), ]
```

```{r}
ggplot(m_0.2, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=0.1) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(~ method) +
  labs(title = 'AR = 0.2', x = 'Time Series Length', y = 'Confidence Interval AR(1) Coefficient Recovery Rate') +
  scale_x_continuous(trans='log2') +
  theme(legend.position="none")
```

```{r}
ar_0.2 <- data.frame(rbind(t(ar_0.2_32[c(1, 6, 17, 16)]), t(ar_0.2_32[c(1, 10, 19, 18)]), t(ar_0.2_64[c(1, 6, 17, 16)]), t(ar_0.2_64[c(1, 10, 19, 18)]), t(ar_0.2_128[c(1, 6, 17, 16)]), t(ar_0.2_128[c(1, 10, 19, 18)]), t(ar_0.2_256[c(1, 6, 17, 16)]), t(ar_0.2_256[c(1, 10, 19, 18)]), t(ar_0.2_512[c(1, 6, 17, 16)]), t(ar_0.2_512[c(1, 10, 19, 18)]), t(ar_0.2_1024[c(1, 6, 17, 16)]), t(ar_0.2_1024[c(1, 10, 19, 18)])))
rownames(ar_0.2) <- NULL
colnames(ar_0.2) <- c("n", 'coverage_rate', 'lb', 'ub')
ar_0.2['method'] <- c('nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv')
library(dplyr)
ar_0.2[order(-ar_0.2$n), ]
```
```{r}
ggplot(ar_0.2, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=0.1) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(~ method) +
  labs(title = 'AR = 0.2', x = 'Time Series Length', y = 'Confidence Interval AR(1) Coefficient Recovery Rate') +
  scale_x_continuous(trans='log2') +
  theme(legend.position="none")
```

```{r}
m_0.4 <- data.frame(rbind(t(m_0.4_32[c(1, 6, 17, 16)]), t(m_0.4_32[c(1, 10, 19, 18)]), t(m_0.4_64[c(1, 6, 17, 16)]), t(m_0.4_64[c(1, 10, 19, 18)]), t(m_0.4_128[c(1, 6, 17, 16)]), t(m_0.4_128[c(1, 10, 19, 18)]), t(m_0.4_256[c(1, 6, 17, 16)]), t(m_0.4_256[c(1, 10, 19, 18)]), t(m_0.4_512[c(1, 6, 17, 16)]), t(m_0.4_512[c(1, 10, 19, 18)]), t(m_0.4_1024[c(1, 6, 17, 16)]), t(m_0.4_1024[c(1, 10, 19, 18)]), t(m_0.4_2048[c(1, 6, 17, 16)]), t(m_0.4_2048[c(1, 10, 19, 18)])))
rownames(m_0.4) <- NULL
colnames(m_0.4) <- c("n", 'coverage_rate', 'lb', 'ub')
m_0.4['method'] <- c('nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv')
library(dplyr)
m_0.4[order(-m_0.4$n), ]
```

```{r}
ggplot(m_0.4, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=0.1) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(~ method) +
  labs(title = 'AR = 0.4', x = 'Time Series Length', y = 'Confidence Interval AR(1) Coefficient Recovery Rate') +
  scale_x_continuous(trans='log2') +
  theme(legend.position="none")
```

```{r}
ar_0.4 <- data.frame(rbind(t(ar_0.4_32[c(1, 6, 17, 16)]), t(ar_0.4_32[c(1, 10, 19, 18)]), t(ar_0.4_64[c(1, 6, 17, 16)]), t(ar_0.4_64[c(1, 10, 19, 18)]), t(ar_0.4_128[c(1, 6, 17, 16)]), t(ar_0.4_128[c(1, 10, 19, 18)]), t(ar_0.4_256[c(1, 6, 17, 16)]), t(ar_0.4_256[c(1, 10, 19, 18)]), t(ar_0.4_512[c(1, 6, 17, 16)]), t(ar_0.4_512[c(1, 10, 19, 18)]), t(ar_0.4_1024[c(1, 6, 17, 16)]), t(ar_0.4_1024[c(1, 10, 19, 18)]), t(ar_0.4_2048[c(1, 6, 17, 16)]), t(ar_0.4_2048[c(1, 10, 19, 18)])))
rownames(ar_0.4) <- NULL
colnames(ar_0.4) <- c("n", 'coverage_rate', 'lb', 'ub')
ar_0.4['method'] <- c('nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv', 'nm', 'mv')
library(dplyr)
ar_0.4[order(-ar_0.4$n), ]
```
```{r}
ggplot(ar_0.4, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=.1) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(~ method) +
  labs(title = 'AR = 0.4', x = 'Time Series Length', y = 'Confidence Interval AR(1) Coefficient Recovery Rate') +
  scale_x_continuous(trans='log2') +
  theme(legend.position="none")
```
