```{r}
mystat <- function(x) {
    c(mean(x),
      sd(x),
      cor(x[-1], x[-length(x)]))
      # acf(x, lag.max = 1, plot = FALSE)$acf[2])
}

x <- arima.sim(list(ma = .3), n = 1000) / sqrt(1 + .3^2)
mystat(x)
```

```{r}
do1rep <- function(n, theta, statistic, blksize, R = 1000) {
    x <- arima.sim(list(ma = theta), n = n) / sqrt(1 + theta^2)
    bts <- boot::tsboot(x, statistic, l = blksize, sim = "fixed", R = R)
    ## returns a vector with length twice of that of mystat's returned values
    ## each pair forms an interval for one target
    delta <- sweep(bts$t, 2, mystat(x)) 
    # Subtract vector from each row of mystat(x) delta = pseudosample mean - original sample mean
    percentile <- apply(bts$t, 2, quantile, prob = c(.025, .975))
    empirical <- rep(mystat(x), each = 2) - apply(delta, 2, quantile, prob = c(.975, .025))
    # Subtract 97.5 percentile delta from statistic for lower bound, and 2.5 percentile delta from statistic for upper bound
    c(percentile, empirical)
}
do1rep(1000, .3, mystat, 10)
```

```{r}
mychk <- function(sim, target) {
    t <- rep(target, 2) # Iterate through statistic twice
    ret <- rep(NA, length(t))
    for (i in seq_along(t)) {
        ii <- (i - 1) * 2
        ret[i] <- mean(sim[ii + 1,] < t[i] & t[i] < sim[ii + 2,])
    }
    c(ret)
}
y <- replicate(5, do1rep(1000, .3, mystat, 10))
mychk(y, target = c(0, 1, .3 / (1 + .3^2)))
```

```{r}
#### simulation
nrep <- 1000
```

```{r}
## n = 1000
n <- 1000
blksize <- 10
theta <- .3
sim_.3_1k <- replicate(nrep, do1rep(n, theta, mystat, blksize))
mychk(sim_.3_1k, target = c(0, 1, theta / (1 + theta^2)))
```

```{r}
## n = 8000
n <- 8000
blksize <- 20
theta <- .3
sim_.3_8k <- replicate(nrep, do1rep(n, theta, mystat, blksize))
mychk(sim_.3_8k, target = c(0, 1, theta / (1 + theta^2)))
```

