```{r functions, echo = FALSE}
nmblk <- function(n, l) {
  b <- n / l # assuming that is an integer
  idx <- sample(seq(1, n - l + 1, by = l), b, replace = TRUE) # Sample between 1 and n - l + 1, 
  # separating by l, b times
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points 
  # decided by idx
}

mvblk <- function(n, l) {
  b <- n / l
  idx <- sample(1:(n - l + 1), b, replace = TRUE) # Sample any starting point between 1 and n - 1 + 1
  # they can overlap
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points
  # decided by idx
}

blkboot <- function(tseries, statistic, R, l) {
  n <- length(tseries) 
  ## observed statistic
  stat <- statistic(tseries) #stat stores a certain statistic of tseries using a function
  ## nonmoving block bootstrap
  nm.stat <- replicate(R, statistic(tseries[nmblk(n, l)])) # finds the statistic of nm bootstrap and repeats R times
  ## moving block bootstrap
  mv.stat <- replicate(R, statistic(tseries[mvblk(n, l)])) # finds the statistic of mv bootstrap and repeats R times
  list(stat = stat, nm.stat = nm.stat, mv.stat = mv.stat) # returns list of three values
}

do1rep <- function(n, theta, sd, l, statistic) {
  x <- arima.sim(list(ar = theta), n = n, sd = sqrt((sd^2)*(1-theta^2))) 
  
  # sd is the standard deviation of the noise -> true_variance(X_t) = sd^2/(1 - theta^2)
  
  bt <- blkboot(x, statistic, 1000, l) 

 # nm_lower_bound with quantile function
  
  nm_interval = quantile(bt$nm.stat, probs = c(0.025, 0.975))
  mv_interval = quantile(bt$mv.stat, probs = c(0.025, 0.975))
  
  nm_contains = FALSE
  if (nm_interval[1] < 0 && nm_interval[2] > 0)
  {
    nm_contains = TRUE
  }
  mv_contains = FALSE
  if (mv_interval[1] < 0 && mv_interval[2] > 0)
  {
    mv_contains = TRUE
  }
  
  c(bt$stat, sd(bt$nm.stat), nm_interval, nm_contains, sd(bt$mv.stat), mv_interval, mv_contains) 

    # returns statistics and standard error's for nm and mv respectively, standard error (sd(bt$mv.stat) is estimated as the sqrt(sample_variance(X_t) / n)
  
}

do1rep2 <- function(n, theta, sd, l, statistic) {
  x <- rnorm(n = n, sd = sd)
  
  # sd is the standard deviation of the noise -> true_variance(X_t) = sd^2/(1 - theta^2)
  
  bt <- blkboot(x, statistic, 1000, l) 

 # nm_lower_bound with quantile function
  
  nm_interval = quantile(bt$nm.stat, probs = c(0.025, 0.975))
  mv_interval = quantile(bt$mv.stat, probs = c(0.025, 0.975))
  
  nm_contains = FALSE
  if (nm_interval[1] < 0 && nm_interval[2] > 0)
  {
    nm_contains = TRUE
  }
  mv_contains = FALSE
  if (mv_interval[1] < 0 && mv_interval[2] > 0)
  {
    mv_contains = TRUE
  }
  
  c(bt$stat, sd(bt$nm.stat), nm_interval, nm_contains, sd(bt$mv.stat), mv_interval, mv_contains) 

    # returns statistics and standard error's for nm and mv respectively, standard error (sd(bt$mv.stat) is estimated as the sqrt(sample_variance(X_t) / n)
  
}
```

```{r more_functions, echo = False}
options(max.print = 1000000)
ar1 <- function(x) cor(x[-1], x[-length(x)])
m1 <- function(x) mean(x)

my_summary <- function(x)
{
  rm = rowMeans(x)
  c(rm, sd(x[1,]), rm[2] - sd(x[1,]), rm[6] - sd(x[1,]), (rm[2] - sd(x[1,])) / sd(x[1,]), (rm[6] - sd(x[1,])) / sd(x[1,]), rm[5] + qnorm(.975) * sqrt((rm[5] * (1 - rm[5])) / 4000), rm[5] - qnorm(.975) * sqrt((rm[5] * (1 - rm[5])) / 4000),  rm[9] + qnorm(.975) * sqrt((rm[9] * (1 - rm[9])) / 4000), rm[9] - qnorm(.975) * sqrt((rm[9] * (1 - rm[9])) / 4000))
}

```

```{r functions, echo = False}
set.seed(5)
o1 = my_summary(replicate(10, do1rep2(100, 0, 0.1, 10, m1)))
set.seed(5)
o2 = my_summary(replicate(10, do1rep2(100, 0, 0.1, ceiling(sqrt(100)), m1)))
set.seed(5)
o3 = my_summary(replicate(10, do1rep2(100, 0, 0.1, ceiling(100**(1/3)), m1)))
o = c(o1, o2, o3)
test <- data.frame(c(100, 10, ceiling(sqrt(100)), ceiling(100**(1/3)), o))
for(m in 4:1)
{
  n = 20 * m
  l1 = 10
  l2 = ceiling(sqrt(n))
  l3 = ceiling(n**(1/3))
  set.seed(5)
  t1 = my_summary(replicate(10, do1rep2(n, 0, 0.1, l1, m1)))
  set.seed(5)
  t2 = my_summary(replicate(10, do1rep2(n, 0, 0.1, l2, m1)))
  set.seed(5)
  t3 = my_summary(replicate(10, do1rep2(n, 0, 0.1, l3, m1)))
  t = c(t1, t2, t3)
  test <- cbind(test, c(n, l1, l2, l3, t))
  
}

print(test)
```
```{r}
five_sims <- function(N, f, R, AR) {
  set.seed(5)
  o1 = my_summary(replicate(R, f(N, AR, 0.1, 10, m1)))
  set.seed(5)
  o2 = my_summary(replicate(R, f(N, AR, 0.1, ceiling(sqrt(N)), m1)))
  set.seed(5)
  o3 = my_summary(replicate(R, f(N, AR, 0.1, ceiling(N**(1/3)), m1)))
  o = c(o1, o2, o3)
  test <- data.frame(c(N, 10, ceiling(sqrt(N)), ceiling(N**(1/3)), o))
  for(m in ((N/20) - 1):((N/20) - 4))
  {
    n = 20 * m
    l1 = 10
    l2 = ceiling(sqrt(n))
    l3 = ceiling(n**(1/3))
    set.seed(5)
    t1 = my_summary(replicate(R, f(n, AR, 0.1, l1, m1)))
    set.seed(5)
    t2 = my_summary(replicate(R, f(n, AR, 0.1, l2, m1)))
    set.seed(5)
    t3 = my_summary(replicate(R, f(n, AR, 0.1, l3, m1)))
    t = c(t1, t2, t3)
    test <- cbind(test, c(n, l1, l2, l3, t))
  
  }
  return(data.frame(test))
}
```

```{r}
print(five_sims(100, do1rep2, 10, 0))
```


```{r Normal, 400 - 320, echo = False}
(norm_1 <- five_sims(400, do1rep2, 4000, 0))
```

```{r Normal, 300 - 220, echo = False}
(norm_2 <- five_sims(300, do1rep2, 4000, 0))
```

```{r Normal, 200 - 120, echo = False}
(norm_3 <- five_sims(200, do1rep2, 4000, 0))
```

```{r Normal, 100 - 20, echo = False}
(norm_4 <- five_sims(100, do1rep2, 4000, 0))
```

```{r AR = 0.2, 400 - 320, echo = False}
(ar_0.2_1 <- five_sims(400, do1rep, 4000, 0.2))
```

```{r AR = 0.2, 300 - 220, echo = False}
(ar_0.2_2 <- five_sims(300, do1rep, 4000, 0.2))
```

```{r AR = 0.2, 200 - 120, echo = False}
(ar_0.2_3 <- five_sims(200, do1rep, 4000, 0.2))
```

```{r AR = 0.2, 100 - 20, echo = False}
(ar_0.2_4 <- five_sims(100, do1rep, 4000, 0.2))
```

```{r AR = 0.4, 600 - 520, echo = False}
(ar_0.4_1 <- five_sims(600, do1rep, 4000, 0.4))
```

```{r AR = 0.4, 500 - 420, echo = False}
(ar_0.4_2 <- five_sims(500, do1rep, 4000, 0.4))
```

```{r AR = 0.4, 400 - 320, echo = False}
(ar_0.4_3 <- five_sims(400, do1rep, 4000, 0.4))
```

```{r AR = 0.4, 300 - 220, echo = False}
(ar_0.4_4 <- five_sims(300, do1rep, 4000, 0.4))
```

```{r AR = 0.4, 200 - 120, echo = False}
(ar_0.4_5 <- five_sims(200, do1rep, 4000, 0.4))
```

```{r AR = 0.4, 100 - 20, echo = False}
(ar_0.4_6 <- five_sims(100, do1rep, 4000, 0.4))
```

```{r AR = 0.6, 900 - 820, echo = False}
(ar_0.6_1 <- five_sims(900, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 800 - 720, echo = False}
(ar_0.6_2 <- five_sims(800, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 700 - 620, echo = False}
(ar_0.6_3 <- five_sims(700, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 600 - 520, echo = False}
(ar_0.6_4 <- five_sims(600, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 500 - 420, echo = False}
(ar_0.6_5 <- five_sims(500, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 400 - 320, echo = False}
(ar_0.6_6 <- five_sims(400, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 300 - 220, echo = False}
(ar_0.6_7 <- five_sims(300, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 200 - 120, echo = False}
(ar_0.6_8 <- five_sims(200, do1rep, 4000, 0.6))
```

```{r AR = 0.6, 100 - 20, echo = False}
(ar_0.6_9 <- five_sims(100, do1rep, 4000, 0.6))
```
```{r}
norm <- data.frame(rbind(t(norm_1[c(1, 2, 9, 20, 19),]), t(norm_1[c(1, 2, 13, 22, 21),]), t(norm_2[c(1, 2, 9, 20, 19),]), t(norm_2[c(1, 2, 13, 22, 21),]), t(norm_3[c(1, 2, 9, 20, 19),]), t(norm_3[c(1, 2, 13, 22, 21),]), t(norm_4[c(1, 2, 9, 20, 19),]), t(norm_4[c(1, 2, 13, 22, 21),]), t(norm_1[c(1, 4, 45, 56, 55),]), t(norm_1[c(1, 4, 49, 58, 57),]), t(norm_2[c(1, 4, 45, 56, 55),]), t(norm_2[c(1, 4, 49, 58, 57),]), t(norm_3[c(1, 4, 45, 56, 55),]), t(norm_3[c(1, 4, 49, 58, 57),]), t(norm_4[c(1, 4, 45, 56, 55),]), t(norm_4[c(1, 4, 49, 58, 57),])))
rownames(norm) <- NULL
colnames(norm) <- c("n", "l", 'coverage_rate', 'lb', 'ub')
norm['method'] <- c('nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv')
library(dplyr)
norm <- tibble::rowid_to_column(norm, "index")
norm <- norm %>%
  mutate(l_func = case_when(
    index < 41 ~ "c",
    index > 40 & index < 81 ~ "cbrt",
    index > 80 ~ "cbrt"
    ))
norm[order(-norm$n), ]
```

```{r}
library(ggplot2)
ggplot(norm, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=5) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(method ~ l_func, labeller=labeller(method = c(mv = 'Moving Method', nm = 'Non-Moving Method'), l_func = c(c = 'l = 10', sqrt = 'l = sqrt(n)', cbrt = 'l = n^(1/3)'))) +
  labs(title = 'AR = 0', x = 'Time Series Length', y = 'Confidence Interval Mean Recovery Rate', color = 'Method') +
  theme(legend.position="none") +
  scale_color_manual(labels = c("Moving Method", "Non-Moving Method"), values = c("blue", "red"))
ggsave('norm.pdf', height = 5)
```
```{r}
ar_0.2 <- data.frame(rbind(t(ar_0.2_1[c(1, 2, 9, 20, 19),]), t(ar_0.2_1[c(1, 2, 13, 22, 21),]), t(ar_0.2_2[c(1, 2, 9, 20, 19),]), t(ar_0.2_2[c(1, 2, 13, 22, 21),]), t(ar_0.2_3[c(1, 2, 9, 20, 19),]), t(ar_0.2_3[c(1, 2, 13, 22, 21),]), t(ar_0.2_4[c(1, 2, 9, 20, 19),]), t(ar_0.2_4[c(1, 2, 13, 22, 21),]), t(ar_0.2_1[c(1, 4, 45, 56, 55),]), t(ar_0.2_1[c(1, 4, 49, 58, 57),]), t(ar_0.2_2[c(1, 4, 45, 56, 55),]), t(ar_0.2_2[c(1, 4, 49, 58, 57),]), t(ar_0.2_3[c(1, 4, 45, 56, 55),]), t(ar_0.2_3[c(1, 4, 49, 58, 57),]), t(ar_0.2_4[c(1, 4, 45, 56, 55),]), t(ar_0.2_4[c(1, 4, 49, 58, 57),])))
rownames(ar_0.2) <- NULL
colnames(ar_0.2) <- c("n", "l", 'coverage_rate', 'lb', 'ub')
ar_0.2['method'] <- c('nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv')
library(dplyr)
ar_0.2 <- tibble::rowid_to_column(ar_0.2, "index")
ar_0.2 <- ar_0.2 %>%
  mutate(l_func = case_when(
    index < 41 ~ "c",
    index > 40 & index < 81 ~ "cbrt",
    index > 80 ~ "cbrt"
    ))
ar_0.2[order(-ar_0.2$n), ]
```

```{r}
ggplot(ar_0.2, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=5) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(method ~ l_func, labeller=labeller(method = c(mv = 'Moving Method', nm = 'Non-Moving Method'), l_func = c(c = 'l = 10', sqrt = 'l = sqrt(n)', cbrt = 'l = n^(1/3)'))) +
  labs(title = 'AR = 0.2', x = 'Time Series Length', y = 'Confidence Interval Mean Recovery Rate', color = 'Method') +
  theme(legend.position="none") +
  scale_color_manual(labels = c("Moving Method", "Non-Moving Method"), values = c("blue", "red"))
ggsave('ar_0.2.pdf', height = 5)
```

```{r}
ar_0.4 <- data.frame(rbind(t(ar_0.4_1[c(1, 2, 9, 20, 19),]), t(ar_0.4_1[c(1, 2, 13, 22, 21),]), t(ar_0.4_2[c(1, 2, 9, 20, 19),]), t(ar_0.4_2[c(1, 2, 13, 22, 21),]), t(ar_0.4_3[c(1, 2, 9, 20, 19),]), t(ar_0.4_3[c(1, 2, 13, 22, 21),]), t(ar_0.4_4[c(1, 2, 9, 20, 19),]), t(ar_0.4_4[c(1, 2, 13, 22, 21),]), t(ar_0.4_5[c(1, 2, 9, 20, 19),]), t(ar_0.4_5[c(1, 2, 13, 22, 21),]), t(ar_0.4_6[c(1, 2, 9, 20, 19),]), t(ar_0.4_6[c(1, 2, 13, 22, 21),]), t(ar_0.4_1[c(1, 4, 45, 56, 55),]), t(ar_0.4_1[c(1, 4, 49, 58, 57),]), t(ar_0.4_2[c(1, 4, 45, 56, 55),]), t(ar_0.4_2[c(1, 4, 49, 58, 57),]), t(ar_0.4_3[c(1, 4, 45, 56, 55),]), t(ar_0.4_3[c(1, 4, 49, 58, 57),]), t(ar_0.4_4[c(1, 4, 45, 56, 55),]), t(ar_0.4_4[c(1, 4, 49, 58, 57),]), t(ar_0.4_5[c(1, 4, 45, 56, 55),]), t(ar_0.4_5[c(1, 4, 49, 58, 57),]), t(ar_0.4_6[c(1, 4, 45, 56, 55),]), t(ar_0.4_6[c(1, 4, 49, 58, 57),])))
rownames(ar_0.4) <- NULL
colnames(ar_0.4) <- c("n", "l", 'coverage_rate', 'lb', 'ub')
ar_0.4['method'] <- c('nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv')
library(dplyr)
ar_0.4 <- tibble::rowid_to_column(ar_0.4, "index")
ar_0.4 <- ar_0.4 %>%
  mutate(l_func = case_when(
    index < 61 ~ "c",
    index > 60 & index < 121  ~ "cbrt",
    index > 120 ~ "cbrt"
    ))
ar_0.4[order(-ar_0.4$n), ]
```

```{r}
ggplot(ar_0.4, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=7.5) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(method ~ l_func, labeller=labeller(method = c(mv = 'Moving Method', nm = 'Non-Moving Method'), l_func = c(c = 'l = 10', sqrt = 'l = sqrt(n)', cbrt = 'l = n^(1/3)'))) +
  labs(title = 'AR = 0.4', x = 'Time Series Length', y = 'Confidence Interval Mean Recovery Rate', color = 'Method') +
  theme(legend.position="none") +
  scale_color_manual(labels = c("Moving Method", "Non-Moving Method"), values = c("blue", "red"))
ggsave('ar_0.4.pdf', height = 5)
```
```{r}
ar_0.6 <- data.frame(rbind(t(ar_0.6_1[c(1, 2, 9, 20, 19),]), t(ar_0.6_1[c(1, 2, 13, 22, 21),]), t(ar_0.6_2[c(1, 2, 9, 20, 19),]), t(ar_0.6_2[c(1, 2, 13, 22, 21),]), t(ar_0.6_3[c(1, 2, 9, 20, 19),]), t(ar_0.6_3[c(1, 2, 13, 22, 21),]), t(ar_0.6_4[c(1, 2, 9, 20, 19),]), t(ar_0.6_4[c(1, 2, 13, 22, 21),]), t(ar_0.6_5[c(1, 2, 9, 20, 19),]), t(ar_0.6_5[c(1, 2, 13, 22, 21),]), t(ar_0.6_6[c(1, 2, 9, 20, 19),]), t(ar_0.6_6[c(1, 2, 13, 22, 21),]), t(ar_0.6_7[c(1, 2, 9, 20, 19),]), t(ar_0.6_7[c(1, 2, 13, 22, 21),]), t(ar_0.6_8[c(1, 2, 9, 20, 19),]), t(ar_0.6_8[c(1, 2, 13, 22, 21),]), t(ar_0.6_9[c(1, 2, 9, 20, 19),]), t(ar_0.6_9[c(1, 2, 13, 22, 21),]), t(ar_0.6_1[c(1, 4, 45, 56, 55),]), t(ar_0.6_1[c(1, 4, 49, 58, 57),]), t(ar_0.6_2[c(1, 4, 45, 56, 55),]), t(ar_0.6_2[c(1, 4, 49, 58, 57),]), t(ar_0.6_3[c(1, 4, 45, 56, 55),]), t(ar_0.6_3[c(1, 4, 49, 58, 57),]), t(ar_0.6_4[c(1, 4, 45, 56, 55),]), t(ar_0.6_4[c(1, 4, 49, 58, 57),]), t(ar_0.6_5[c(1, 4, 45, 56, 55),]), t(ar_0.6_5[c(1, 4, 49, 58, 57),]), t(ar_0.6_6[c(1, 4, 45, 56, 55),]), t(ar_0.6_6[c(1, 4, 49, 58, 57),]), t(ar_0.6_7[c(1, 4, 45, 56, 55),]), t(ar_0.6_7[c(1, 4, 49, 58, 57),]), t(ar_0.6_8[c(1, 4, 45, 56, 55),]), t(ar_0.6_8[c(1, 4, 49, 58, 57),]), t(ar_0.6_9[c(1, 4, 45, 56, 55),]), t(ar_0.6_9[c(1, 4, 49, 58, 57),])))
rownames(ar_0.6) <- NULL
colnames(ar_0.6) <- c("n", "l", 'coverage_rate', 'lb', 'ub')
ar_0.6['method'] <- c('nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv', 'nm', 'nm', 'nm', 'nm', 'nm', 'mv', 'mv', 'mv', 'mv', 'mv')
library(dplyr)
ar_0.6 <- tibble::rowid_to_column(ar_0.6, "index")
ar_0.6 <- ar_0.6 %>%
  mutate(l_func = case_when(
    index < 91 ~ "c",
    index > 90 & index < 181  ~ "cbrt",
    index > 180 ~ "cbrt"
    ))
ar_0.6[order(-ar_0.6$n), ]
```

```{r}
ggplot(ar_0.6, aes(x = n, y = coverage_rate, color = method)) +
  geom_hline(yintercept = .95, linetype = 'dashed', color = 'orange') + 
  geom_errorbar(aes(ymin=lb, ymax=ub), colour="black", width=10) +
  geom_line() +
  geom_point(size = 0.5) +
  facet_grid(method ~ l_func, labeller=labeller(method = c(mv = 'Moving Method', nm = 'Non-Moving Method'), l_func = c(c = 'l = 10', sqrt = 'l = sqrt(n)', cbrt = 'l = n^(1/3)'))) +
  labs(title = 'AR = 0.6', x = 'Time Series Length', y = 'Confidence Interval Mean Recovery Rate', color = 'Method') +
  theme(legend.position="none") +
  scale_color_manual(labels = c("Moving Method", "Non-Moving Method"), values = c("blue", "red"))
ggsave('ar_0.6.pdf', height = 5)
```
