```{r}
df_bts <- function(cov, nrep = 1000, phis = c(-0.4, -0.2, 0, 0.2, 0.4), sizes = c(100, 200, 300, 400, 500, 600, 700), types = c('pctCI', 'estCI', 'bcaCIest'), parameters = c('mu', 'sigma', 'phi')) {
  phi <- rep(phis, each = length(sizes) * length(types) * length(parameters))
  n <- rep(sizes, times = length(phis), each = length(types) * length(parameters))
  CI <- rep(types, times = length(phis) * length(sizes), each = length(parameters))
  t <- rep(parameters, times = length(phis) * length(types) * length(sizes))
  LB <- sapply(cov, function(i) prop.test(i*nrep, nrep)$conf.int[1])
  UB <- sapply(cov, function(i) prop.test(i*nrep, nrep)$conf.int[2])
  
  c(data.frame(phi, n, CI, t, cov, LB, UB))
}


```

```{r}
target <- c(0, 1, -.4)
cov <- c(mychk(sim_n.4_1h, target), mychk(sim_n.4_2h, target), mychk(sim_n.4_3h, target), mychk(sim_n.4_4h, target), mychk(sim_n.4_5h, target), mychk(sim_n.4_6h, target), mychk(sim_n.4_7h, target))
target <- c(0, 1, -.2)
cov <- c(cov, mychk(sim_n.2_1h, target), mychk(sim_n.2_2h, target), mychk(sim_n.2_3h, target), mychk(sim_n.2_4h, target), mychk(sim_n.2_5h, target), mychk(sim_n.2_6h, target), mychk(sim_n.2_7h, target))
target <- c(0, 1, 0)
cov <- c(cov, mychk(sim_0_1h, target), mychk(sim_0_2h, target), mychk(sim_0_3h, target), mychk(sim_0_4h, target), mychk(sim_0_5h, target), mychk(sim_0_6h, target), mychk(sim_0_7h, target))
target <- c(0, 1, .2)
cov <- c(cov, mychk(sim_.2_1h, target), mychk(sim_.2_2h, target), mychk(sim_.2_3h, target), mychk(sim_.2_4h, target), mychk(sim_.2_5h, target), mychk(sim_.2_6h, target), mychk(sim_.2_7h, target)) 
target <- c(0, 1, .4)
cov <- c(cov, mychk(sim_.4_1h, target), mychk(sim_.4_2h, target), mychk(sim_.4_3h, target), mychk(sim_.4_4h, target), mychk(sim_.4_5h, target), mychk(sim_.4_6h, target), mychk(sim_.4_7h, target))

df <- data.frame(df_bts(cov))
graph_bts <- function(t, width, data, trans = 'identity', level = .95)
{
  library(latex2exp)
  library(ggplot2)

  ggplot(data, aes(x = n, y = cov)) +
    geom_hline(yintercept = level, linetype = 'dashed', color = 'orange') + 
    geom_line() +
    geom_errorbar(aes(ymin=LB, ymax = UB), colour="black", width = width) +
    facet_grid(factor(phi) ~ factor(CI), labeller = label_parsed) +
    scale_y_continuous(trans=trans)
  ggsave(paste('../Manuscript/figures/plot_', t, '.pdf', sep = ''))
}
```

```{r}
t <- 'mu'
width <- 10
df1 <- df[(df$t == t),]
graph_bts(t, width, df1)
```

```{r}
t <- 'sigma'
width <- 10
df2 <- df[(df$t == t),]
graph_bts(t, width, df2)
```

```{r}
t <- 'phi'
width <- 10
df3 <- df[(df$t == t),]
graph_bts(t, width, df3)
```



