```{r}
numeric2 <- function(theta) {
  if (theta == 0) {
    c(numeric(0))
  }
  else {
    c(theta)
  }
}
numeric2(0) # Returns numeric (0) when theta is 0
numeric2(0.2) # Returns theta when theta is not 0, this ensures that the arima simulation runs without a warning
```

```{r functions, echo = FALSE}
nmblk <- function(n, l) {
  b <- n / l # assuming that is an integer
  idx <- sample(seq(1, n - l + 1, by = l), b, replace = TRUE) # Sample between 1 and n - l + 1, 
  # separating by l, b times
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points 
  # decided by idx
}

mvblk <- function(n, l) {
  b <- n / l
  idx <- sample(1:(n - l + 1), b, replace = TRUE) # Sample any starting point between 1 and n - 1 + 1
  # they can overlap
  c(outer(0:(l - 1), idx, "+")) # Creates a vector listing random blocks of size l with starting points
  # decided by idx
}

blkboot <- function(tseries, statistic, R, l) {
  n <- length(tseries) 
  ## observed statistic
  stat <- statistic(tseries) #stat stores a certain statistic of tseries using a function
  ## nonmoving block bootstrap
  nm.stat <- replicate(R, statistic(tseries[nmblk(n, l)])) # finds the statistic of nm bootstrap and repeats R times
  ## moving block bootstrap
  mv.stat <- replicate(R, statistic(tseries[mvblk(n, l)])) # finds the statistic of mv bootstrap and repeats R times
  list(stat = stat, nm.stat = nm.stat, mv.stat = mv.stat) # returns list of three values
}

do1rep <- function(n, theta, sigma,
                   target,
                   len, statistic, B = 1000) {
  x <- arima.sim(list(ar = numeric2(theta)), n = n, sd = sigma * sqrt(1-theta^2))
  ## sd is the standard deviation of the noise -> true_variance(X_t) = sd^2/(1 - theta^2)
  bt <- blkboot(x, statistic, B, len) 

  ## two intervals for each statistic
  ret <- c()
  num <- dim(bt$nm.stat)[1]
  for (s in 1:num) {
    nm = quantile(bt$nm.stat[s,], probs = c(0.025, 0.975))
    ret <- append(ret, nm[1] < target[s] && target[s] < nm[2])
    mv = quantile(bt$mv.stat[s,], probs = c(0.025, 0.975))
    ret <- append(ret, mv[1] < target[s] && target[s] < mv[2])
  }
  
  ## c(bt$stat, sd(bt$nm.stat), nm_interval, nm_contains, sd(bt$mv.stat), mv_interval, mv_contains) 

  ## returns statistics and standard error's for nm and mv respectively, standard error (sd(bt$mv.stat) is estimated as the sqrt(sample_variance(X_t) / n)
  #c(nm.cov, mv.cov)
  c(ret)
}

```

```{r more_functions, echo = False}
options(max.print = 1000000)
#ar1 <- function(x) cor(x[-1], x[-length(x)])
ar1 <- function(x) c(acf(x, plot = FALSE, lag.max = 1)$acf)[2]
m1 <- function(x) mean(x)
s1 <- function(x) c(mean(x), acf(x, plot = FALSE, lag.max = 1)$acf[2], var(x))

my_summary <- function(x, alpha = .05)
{
  n = dim(x)[2]
  ret <- c()
  rm = rowMeans(x)
  for (s in rm) {
    ret = append(ret, c(s, s - qnorm(1 - alpha/2) * sqrt((s * (1 - s)) / n), s + qnorm(1 - alpha/2) * sqrt((s * (1 - s)) / n)))
  }
  c(ret)
}

```

```{r Theta = 0, Sigma = 0.1, n = 32}
my.summary <- data.frame(matrix(ncol = 21, nrow = 0))
colnames(my.summary) <- c('theta', 'sigma', 'n', 'nm.cov.mu', 'nm.lower.mu', 'nm.upper.mu', 'mv.cov.mu', 'mv.lower.mu', 'mv.upper.mu', 'nm.cov.theta', 'nm.lower.theta', 'nm.upper.theta', 'mv.cov.theta', 'mv.lower.theta', 'mv.upper.theta', 'nm.cov.sigsq', 'nm.lower.sigsq', 'nm.upper.sigsq', 'mv.cov.sigsq', 'mv.lower.sigsq', 'mv.upper.sigsq')
nrep <- 4000
statistic <- s1
mu <- 0
theta <- 0
sigma <- 0.1
set.seed(1)
n <- 32
d_0_0.1_32 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.1_32)))
```

```{r Theta = 0, Sigma = 0.1, n = 64}
set.seed(5)
n <- 64
d_0_0.1_64 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.1_64)))
```

```{r Theta = 0, Sigma = 0.1, n = 128}
set.seed(25)
n <- 128
d_0_0.1_128 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.1_128)))
```

```{r Theta = 0, Sigma = 0.1, n = 256}
set.seed(125)
n <- 256
d_0_0.1_256 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.1_256)))
```

```{r Theta = 0, Sigma = 0.1, n = 512}
set.seed(625)
n <- 512
d_0_0.1_512 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.1_512)))
```

```{r Theta = 0, Sigma = 0.1, n = 1024}
set.seed(3125)
n <- 1024
d_0_0.1_1024 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.1_1024)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 32}
theta <- 0.2
set.seed(3)
n <- 32
d_0.2_0.1_32 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_32)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 64}
set.seed(15)
n <- 64
d_0.2_0.1_64 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_64)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 128}
set.seed(75)
n <- 128
d_0.2_0.1_128 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_128)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 256}
set.seed(375)
n <- 256
d_0.2_0.1_256 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_256)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 512}
set.seed(1875)
n <- 512
d_0.2_0.1_512 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_512)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 1024}
set.seed(9375)
n <- 1024
d_0.2_0.1_1024 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_1024)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 2048}
set.seed(46875)
n <- 2048
d_0.2_0.1_2048 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_2048)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 4096}
set.seed(234375)
n <- 4096
d_0.2_0.1_4096 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_4096)))
```

```{r Theta = 0.2, Sigma = 0.1, n = 8192}
set.seed(1171875)
n <- 8192
d_0.2_0.1_8192 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.1_8192)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 32}
theta <- 0.4
set.seed(5)
n <- 32
d_0.4_0.1_32 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_32)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 64}
set.seed(25)
n <- 64
d_0.4_0.1_64 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_64)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 128}
set.seed(125)
n <- 128
d_0.4_0.1_128 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_128)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 256}
set.seed(625)
n <- 256
d_0.4_0.1_256 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_256)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 512}
set.seed(3125)
n <- 512
d_0.4_0.1_512 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_512)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 1024}
set.seed(15625)
n <- 1024
d_0.4_0.1_1024 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_1024)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 2048}
set.seed(78125)
n <- 2048
d_0.4_0.1_2048 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_2048)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 4096}
set.seed(390625)
n <- 4096
d_0.4_0.1_4096 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_4096)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 8192}
set.seed(1953125)
n <- 8192
d_0.4_0.1_8192 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_8192)))
```

```{r Theta = 0.4, Sigma = 0.1, n = 16384}
set.seed(9765625)
n <- 16384
d_0.4_0.1_16384 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.1_16384)))
```

```{r Theta = 0, Sigma = 0.5, n = 32}
theta <- 0
sigma <- 0.5
set.seed(1)
n <- 32
d_0_0.5_32 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.5_32)))
```

```{r Theta = 0, Sigma = 0.5, n = 64}
set.seed(5)
n <- 64
d_0_0.5_64 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.5_64)))
```

```{r Theta = 0, Sigma = 0.5, n = 128}
set.seed(25)
n <- 128
d_0_0.5_128 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.5_128)))
```

```{r Theta = 0, Sigma = 0.5, n = 256}
set.seed(125)
n <- 256
d_0_0.5_256 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.5_256)))
```

```{r Theta = 0, Sigma = 0.5, n = 512}
set.seed(625)
n <- 512
d_0_0.5_512 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.5_512)))
```

```{r Theta = 0, Sigma = 0.5, n = 1024}
set.seed(3125)
n <- 1024
d_0_0.5_1024 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0_0.5_1024)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 32}
theta <- 0.2
set.seed(3)
n <- 32
d_0.2_0.5_32 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_32)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 64}
set.seed(15)
n <- 64
d_0.2_0.5_64 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_64)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 128}
set.seed(75)
n <- 128
d_0.2_0.5_128 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_128)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 256}
set.seed(375)
n <- 256
d_0.2_0.5_256 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_256)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 512}
set.seed(1875)
n <- 512
d_0.2_0.5_512 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_512)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 1024}
set.seed(9375)
n <- 1024
d_0.2_0.5_1024 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_1024)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 2048}
set.seed(46875)
n <- 2048
d_0.2_0.5_2048 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_2048)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 4096}
set.seed(234375)
n <- 4096
d_0.2_0.5_4096 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_4096)))
```

```{r Theta = 0.2, Sigma = 0.5, n = 8192}
set.seed(1171875)
n <- 8192
d_0.2_0.5_8192 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.2_0.5_8192)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 32}
theta <- 0.4
set.seed(5)
n <- 32
d_0.4_0.5_32 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_32)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 64}
set.seed(25)
n <- 64
d_0.4_0.5_64 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_64)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 128}
set.seed(125)
n <- 128
d_0.4_0.5_128 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_128)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 256}
set.seed(625)
n <- 256
d_0.4_0.5_256 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_256)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 512}
set.seed(3125)
n <- 512
d_0.4_0.5_512 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_512)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 1024}
set.seed(15625)
n <- 1024
d_0.4_0.5_1024 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_1024)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 2048}
set.seed(78125)
n <- 2048
d_0.4_0.5_2048 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_2048)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 4096}
set.seed(390625)
n <- 4096
d_0.4_0.5_4096 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_4096)))
```

```{r Theta = 0.4, Sigma = 0.5, n = 8192}
set.seed(1953125)
n <- 8192
d_0.4_0.5_8192 <- replicate(nrep, do1rep(n, theta, sigma, c(mu, theta, sigma^2), ceiling(n**(1/3)), statistic))
(my.summary[nrow(my.summary) + 1,] <- c(theta, sigma, n, my_summary(d_0.4_0.5_8192)))
```

```{r}
my.summary
```


```{r}
library(tidyr)
(summary.df <- my.summary %>%
  pivot_longer(
    cols = nm.cov.mu:mv.upper.sigsq,
    names_to = c('method', '.value', 'target'),
    names_pattern = "(.*)\\.(.*)\\.(.*)"
  ))
write.csv(summary.df,"../Data/summary.df.csv", row.names = FALSE)
```


```{r}
write.csv(my.summary,"../Data/my.summary.csv", row.names = FALSE)
```

```{r}
write.csv(d_0_0.1_32,"../Data/Raw/d_0_0.1_32.csv", row.names = FALSE)
write.csv(d_0_0.1_64,"../Data/Raw/d_0_0.1_64.csv", row.names = FALSE)
write.csv(d_0_0.1_128,"../Data/Raw/d_0_0.1_128.csv", row.names = FALSE)
write.csv(d_0_0.1_256,"../Data/Raw/d_0_0.1_256.csv", row.names = FALSE)
write.csv(d_0_0.1_512,"../Data/Raw/d_0_0.1_512.csv", row.names = FALSE)
write.csv(d_0_0.1_1024,"../Data/Raw/d_0_0.1_1024.csv", row.names = FALSE)
write.csv(d_0.2_0.1_32,"../Data/Raw/d_0.2_0.1_32.csv", row.names = FALSE)
write.csv(d_0.2_0.1_64,"../Data/Raw/d_0.2_0.1_64.csv", row.names = FALSE)
write.csv(d_0.2_0.1_128,"../Data/Raw/d_0.2_0.1_128.csv", row.names = FALSE)
write.csv(d_0.2_0.1_256,"../Data/Raw/d_0.2_0.1_256.csv", row.names = FALSE)
write.csv(d_0.2_0.1_512,"../Data/Raw/d_0.2_0.1_512.csv", row.names = FALSE)
write.csv(d_0.2_0.1_1024,"../Data/Raw/d_0.2_0.1_1024.csv", row.names = FALSE)
write.csv(d_0.2_0.1_2048,"../Data/Raw/d_0.2_0.1_2048.csv", row.names = FALSE)
write.csv(d_0.2_0.1_4096,"../Data/Raw/d_0.2_0.1_4096.csv", row.names = FALSE)
write.csv(d_0.2_0.1_8192,"../Data/Raw/d_0.2_0.1_8192.csv", row.names = FALSE)
write.csv(d_0.4_0.1_32,"../Data/Raw/d_0.4_0.1_32.csv", row.names = FALSE)
write.csv(d_0.4_0.1_64,"../Data/Raw/d_0.4_0.1_64.csv", row.names = FALSE)
write.csv(d_0.4_0.1_128,"../Data/Raw/d_0.4_0.1_128.csv", row.names = FALSE)
write.csv(d_0.4_0.1_256,"../Data/Raw/d_0.4_0.1_256.csv", row.names = FALSE)
write.csv(d_0.4_0.1_512,"../Data/Raw/d_0.4_0.1_512.csv", row.names = FALSE)
write.csv(d_0.4_0.1_1024,"../Data/Raw/d_0.4_0.1_1024.csv", row.names = FALSE)
write.csv(d_0.4_0.1_2048,"../Data/Raw/d_0.4_0.1_2048.csv", row.names = FALSE)
write.csv(d_0.4_0.1_4096,"../Data/Raw/d_0.4_0.1_4096.csv", row.names = FALSE)
write.csv(d_0.4_0.1_8192,"../Data/Raw/d_0.4_0.1_8192.csv", row.names = FALSE)
write.csv(d_0.4_0.1_16384,"../Data/Raw/d_0.4_0.1_16384.csv", row.names = FALSE)
write.csv(d_0_0.5_32,"../Data/Raw/d_0_0.5_32.csv", row.names = FALSE)
write.csv(d_0_0.5_64,"../Data/Raw/d_0_0.5_64.csv", row.names = FALSE)
write.csv(d_0_0.5_128,"../Data/Raw/d_0_0.5_128.csv", row.names = FALSE)
write.csv(d_0_0.5_256,"../Data/Raw/d_0_0.5_256.csv", row.names = FALSE)
write.csv(d_0_0.5_512,"../Data/Raw/d_0_0.5_512.csv", row.names = FALSE)
write.csv(d_0_0.5_1024,"../Data/Raw/d_0_0.5_1024.csv", row.names = FALSE)
write.csv(d_0.2_0.5_32,"../Data/Raw/d_0.2_0.5_32.csv", row.names = FALSE)
write.csv(d_0.2_0.5_64,"../Data/Raw/d_0.2_0.5_64.csv", row.names = FALSE)
write.csv(d_0.2_0.5_128,"../Data/Raw/d_0.2_0.5_128.csv", row.names = FALSE)
write.csv(d_0.2_0.5_256,"../Data/Raw/d_0.2_0.5_256.csv", row.names = FALSE)
write.csv(d_0.2_0.5_512,"../Data/Raw/d_0.2_0.5_512.csv", row.names = FALSE)
write.csv(d_0.2_0.5_1024,"../Data/Raw/d_0.2_0.5_1024.csv", row.names = FALSE)
write.csv(d_0.2_0.5_2048,"../Data/Raw/d_0.2_0.5_2048.csv", row.names = FALSE)
write.csv(d_0.2_0.5_4096,"../Data/Raw/d_0.2_0.5_4096.csv", row.names = FALSE)
write.csv(d_0.2_0.5_8192,"../Data/Raw/d_0.2_0.5_8192.csv", row.names = FALSE)
write.csv(d_0.4_0.5_32,"../Data/Raw/d_0.4_0.5_32.csv", row.names = FALSE)
write.csv(d_0.4_0.5_64,"../Data/Raw/d_0.4_0.5_64.csv", row.names = FALSE)
write.csv(d_0.4_0.5_128,"../Data/Raw/d_0.4_0.5_128.csv", row.names = FALSE)
write.csv(d_0.4_0.5_256,"../Data/Raw/d_0.4_0.5_256.csv", row.names = FALSE)
write.csv(d_0.4_0.5_512,"../Data/Raw/d_0.4_0.5_512.csv", row.names = FALSE)
write.csv(d_0.4_0.5_1024,"../Data/Raw/d_0.4_0.5_1024.csv", row.names = FALSE)
write.csv(d_0.4_0.5_2048,"../Data/Raw/d_0.4_0.5_2048.csv", row.names = FALSE)
write.csv(d_0.4_0.5_4096,"../Data/Raw/d_0.4_0.5_4096.csv", row.names = FALSE)
write.csv(d_0.4_0.5_8192,"../Data/Raw/d_0.4_0.5_8192.csv", row.names = FALSE)
write.csv(d_0.4_0.5_16384,"../Data/Raw/d_0.4_0.5_16384.csv", row.names = FALSE)

```

```{r}
tf <- function(df, target, theta) {
  library(reshape2)
  library(dplyr)
  d1 <- melt(df[1:3], id.vars = 'n', variable.name = 'Method', value.name = 'Coverage.Rate')
  levels(d1$Method) <- list(Non.Moving  = "Non.Moving.Coverage.Rate", Moving = "Moving.Coverage.Rate")
  d2 <- melt(df[c(1, 4, 6)], id.vars = 'n', variable.name = 'Method', value.name = 'Lower.Bound')
  levels(d2$Method) <- list(Non.Moving  = "Non.Moving.Lower.Bound", Moving = "Moving.Lower.Bound")
  d3 <- melt(df[c(1, 5, 7)], id.vars = 'nh', variable.name = 'Method', value.name= 'Upper.Bound')
  levels(d3$Method) <- list(Non.Moving  = "Non.Moving.Upper.Bound", Moving = "Moving.Upper.Bound")
  z <- merge(x=d1,y=d2)
  z <- merge(x=z,y=d3)
  z %>%
    mutate(Target = target) %>%
    mutate(Theta = theta)
}
df <- rbind(tf(m_0, 'Mean', 0), tf(m_0.2, 'Mean', 0.2), tf(m_0.4, 'Mean', 0.4), tf(ar_0, 'Theta', 0), tf(ar_0.2, 'Theta', 0.2), tf(ar_0.4, 'Theta', 0.4))
write.csv(df,"../Data/df.csv", row.names = FALSE)
```

```{r}
m_0
```

