---
title: "Visualization"
output: html_document
date: "2022-09-30"
---

```{r}
set.seed(5)
(x <- arima.sim(list(ar = 0.2), n = 50, sd = 1)) 
pdf("orig_ts.pdf", width = 15)
plot.ts(x)
text(x=c(5, 15, 25), y=c(2, 2, 2), labels=c("Block 3, 5", "Block 1", "Block 2, 4"), col="blue")
rect(1, -3, 10, 3, col= rgb(0,0,0,alpha=0.25))
rect(11, -3, 20, 3, col= rgb(0,0,1,alpha=0.25))
rect(21, -3, 30, 3, col= rgb(0,1,0,alpha=0.25))
rect(31, -3, 40, 3, col= rgb(0,1,1,alpha=0))
rect(41, -3, 50, 3, col= rgb(1,0,0,alpha=0))
dev.off()
```

```{r}
set.seed(5)
(y1 <- x[nmblk(50, 10)])
pdf("nm_ts.pdf", width = 15)
plot.ts(y1)
text(x=c(5, 15, 25, 35, 45), y=c(2, 2, 2, 2, 2), labels=c("Block 1", "Block 2", "Block 3", "Block 4", "Block 5"), col="blue")
rect(1, -3, 10, 3, col= rgb(0,0,1,alpha=0.25))
rect(11, -3, 20, 3, col= rgb(0,1,0,alpha=0.25))
rect(21, -3, 30, 3, col= rgb(0,0,0,alpha=0.25))
rect(31, -3, 40, 3, col= rgb(0,1,0,alpha=0.25))
rect(41, -3, 50, 3, col= rgb(0,0,0,alpha=0.25))
dev.off()
```
```{r}
set.seed(5)
(y2 <- x[mvblk(50, 10)])
pdf("mv_ts.pdf", width = 15)
plot.ts(y2)
text(x=c(5, 15, 25, 35, 45), y=c(2, 2, 2, 2, 2), labels=c("Block 1", "Block 2", "Block 3", "Block 4", "Block 5"), col="blue")
rect(1, -3, 10, 3, col= rgb(0,0,0,alpha=0.25))
rect(11, -3, 20, 3, col= rgb(0,0,1,alpha=0.25))
rect(21, -3, 30, 3, col= rgb(0,1,0,alpha=0.25))
rect(31, -3, 40, 3, col= rgb(0,1,1,alpha=0.25))
rect(41, -3, 50, 3, col= rgb(1,0,0,alpha=0.25))
dev.off()
```
```{r}
pdf("orig_ts_2.pdf", width = 15)
plot.ts(x)
rect(2, -3, 11, 3, col= rgb(0,0,0,alpha=0.25))
rect(15, -3, 24, 3, col= rgb(0,0,1,alpha=0.5))
rect(11, -3, 20, 3, col= rgb(0,1,0,alpha=0.25))
rect(41, -3, 50, 3, col= rgb(0,1,1,alpha=0.25))
rect(21, -3, 30, 3, col= rgb(1,0,0,alpha=0.25))
text(x=c(6, 19, 15, 45, 25), y=c(2, -2, 2, 2, 2), labels=c("Block 1", "Block 2", "Block 3", "Block 4", "Block 5"), col="blue")
dev.off()
```
```{r}
set.seed(5)
data <- blkboot(x, m1, 1000, 10)
library(ggplot2)
pdf('nm_dist.pdf')
hist(data$nm.stat, main = 'Distribution of Sample Means from Non-Moving Block Bootstrap', xlab = 'Sample Mean')
dev.off()
pdf('mv_dist.pdf')
hist(data$mv.stat, main = 'Distribution of Sample Means from Moving Block Bootstrap', xlab = 'Sample Mean')
dev.off()
```

```{r}
plot(c(0, 1200), c(600, 1400), type= "n", xlab = "", ylab = "")
xleft = rep(c(200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100), times = 4)
ybottom = rep(c(1200, 900, 600, 0), each = 10)
xright = rep(c(300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200), times = 4)
ytop = rep(c(1400, 1100, 800, 200), each = 10)
rect(xleft = xleft, ybottom = ybottom, xright = xright, ytop = ytop)
rect(xleft = c(200, 500, 900), ybottom = c(1200, 900, 600), xright = c(500, 800, 1200), 
     ytop = c(1400, 1100, 800), col= rgb(1,0,0,alpha=0.25))
x = rep(c(250, 350, 450, 550, 650, 750, 850, 950, 1050, 1150), times = 4)
y = rep(c(1300, 1000, 700, 100), each = 10)
labels = rep(c('X1', 'X2', 'X3', 'X4', 'X5', 'X6', '...', 'Xn-2', 'Xn-1', 'Xn'), times = 4)
text(x=x, y=y, labels=labels)
text(x=100, y=1300, labels='Block 1')
text(x=100, y=1000, labels='Block 2')
text(x=100, y=700, labels='Block n/l')
```



```{r}
plot(c(0, 1200), c(0, 1400), type= "n", xlab = "", ylab = "")
rect(xleft = xleft, ybottom = ybottom, xright = xright, ytop = ytop)
rect(xleft = c(200, 300, 400, 200, 1100), ybottom = c(1200, 900, 600, 0, 0), xright = c(500, 600, 700, 400, 1200), ytop = c(1400, 1100, 800, 200, 200), col= rgb(1,0,0,alpha=0.25))
labels = rep(c('X1', 'X2', 'X3', 'X4', 'X5', 'X6', '...', 'Xn-2', 'Xn-1', 'Xn'), times = 4)
text(x=x, y=y, labels=labels)
text(x=100, y=1300, labels='Block 1')
text(x=100, y=1000, labels='Block 2')
text(x=100, y=700, labels='Block 3')
text(x=100, y=100, labels='Block n')
```

